### ISSUE TITLE
Stat discrepancy

### ISSUE THREAD

**Issue by parad0xSpace** [Sakimori/matteo-the-prestige#128]
Okay so for some context: I'm setting up a private tournament with some friends for my birthday (happy blirthday to me!) and There's something strange happening with one of the players. Their name is Weezie Carter XVII, and their stats are different in Onomancer, when searched for using the m;showplayer command with a team, and when searched for using the m;showplayer command without a team.

Onomancer screencap: https://imgur.com/PRhXU3m
m;showplayer WITH team screencap: https://imgur.com/OKsQOUq
m;showplayer WITHOUT team screencap: https://imgur.com/OKsQOUq

This doesn't happen with any of our other players so I'm not sure what Weezie Carter XVII's deal is. I thought you guys would find it interesting.

**Comment by Sakimori** [comment]
the showplayer command doesn't support team names. it's searching onomancer for the player named "\n Tacomadome Seat-Edges\nWeezie Carter XVII"

**Comment by parad0xSpace** [comment]
I see! Well that solves one half of the mystery, but even without the team name there's a discrepancy between what Onomancer says and what Matteo says.

**Comment by parad0xSpace** [comment]
WHOOPS my bad
https://imgur.com/ys5G435

**Comment by Sakimori** [comment]
that's searching for "\nWeezie Carter XVII", you don't hit enter there
