### ISSUE TITLE
draft command done improperly doesn't error, instead uses "bookmark"

### ISSUE THREAD

**Issue by Sakimori** [Sakimori/matteo-the-prestige#157]
![image](https://user-images.githubusercontent.com/13842188/104793225-89cf9080-576f-11eb-8602-88d7a093247c.png)

**Comment by Sakimori** [comment]
![image](https://user-images.githubusercontent.com/13842188/104793319-ffd3f780-576f-11eb-97aa-bdd9fdc45aba.png)

**Comment by jmaliksi** [comment]
i cannot reproduce the second comment 🤔
