### ISSUE TITLE
the bot does not ignore webhook messages, causing any PluralKit user who runs a command to run it twice

### ISSUE THREAD

**Issue by Genderdruid** [Sakimori/matteo-the-prestige#187]
I'm not sure if this is fixable but it was submitted via the form and is an issue.

**Comment by xSke** [comment]
It's fairly trivial to detect whether a message is sent by a webhook (whether `webhook_id` is present, which I'm sure has a mirror in discord.py). It'll still pick up on the first message so it won't cause any issues for PK users to just ignore 'em :)
