### ISSUE TITLE
custom draft size (suggestion)

### ISSUE THREAD

**Issue by valuminumbandit** [Sakimori/matteo-the-prestige#195]
feature suggestion: might be nice to allow a choice of how many pitchers you want to draft. 1 is great for the dramatic finale of picking a pitcher, but 3 generally seems to be a good sweet spot for the amount of pitchers on a team to keep a league interesting. in terms of making a purely drafted league, right now it seems the only way to have 3 pitchers is to draft separate teams of just pitchers and pick from there, but that comes with lots of opportunities to accidentally see the star ranking of a pitcher too early and spoil the surprise. this absolutely isn't an urgent issue, but i think it'd be pretty convenient to be able to nab 3 pitchers during that initial draft!

**Comment by Sakimori** [comment]
this is a really good idea!!! thanks, i'll work on it when i next look at this
