### ISSUE TITLE
league structure

### ISSUE THREAD

**Issue by Sakimori** [Sakimori/matteo-the-prestige#2]
pull saved teams into a league, run games, generate standings and leaderboards. long-term goal.

**Comment by Sakimori** [comment]
artemis said have a checkbox dropdown to select the weather pool for the league and i for one love this idea (and xer)

**Comment by Sakimori** [comment]
include league day in game end message

**Comment by esSteres** [comment]
frontend currently generates json from user inputs that looks kind of like this, though it can change if needed:
```
{
  structure: {
    name: "string",
    subleagues: [{
      name: "string",
      divisions: [{
        name: "string",
        teams: "string"
      }]
    }]
  },
  games_per_series: 0,
  division_series: 0,
  inter_division_series: 0,
  inter_league_series: 0
}
```
