### ISSUE TITLE
History Box

### ISSUE THREAD

**Issue by hillexed** [Sakimori/matteo-the-prestige#22]
Add a few lines labeled "History" to the bottom of the sim, with history so you don't need to be constantly watching the sim.

One way to do this is to store the last n lines of result['text'] in a queue, so it shows the last n messages.

> History:
> Bottom of 12, x batting.
> Y got out.
> x hit a single!

Another way to do this would be a "notable events" box, which is like recent events but only contains the n last important events, like hits and home runs. Strikes, balls, getting out, double plays, inning change messages, and things like that would have important:false and therefore not put into the important event queue. Showing the inning these things happened on would also help.

> Important Events:
> Bottom of 5: Y scored a home run!
> Top of 2: X hit a single

Both at once could also help.

**Comment by Sakimori** [comment]
"bottom of the sim"?

**Comment by esSteres** [comment]
I believe they mean at the bottom of the game display, under "Supernova"

**Comment by Sakimori** [comment]
ah, okay! i'll consider this. the embed already has a lot of information so no guarantees

**Comment by hillexed** [comment]
it could go anywhere, really. 

One idea, if you needed to save space: you could have the top line in the history box double as the message showing the most recent output. The most recent output could stay where it is now, then the second-most recent output would be right under that, the third-most recent output right under that...
