### ISSUE TITLE
Add team name alongside pitcher and batter names (or some other system to show who is at-bat)

### ISSUE THREAD

**Issue by esSteres** [Sakimori/matteo-the-prestige#24]
e.g.
```
Pitcher:
Lexi Halberd (Kernow Technologists)
Batter:
Daphney Demerit (Deep Space Bandits)
```
I know it's implied by the inning and the title (which does mention who is home and who is away) but I think it would just make for a smoother experience if it were stated explicitly somewhere. Also, we are all love blaseball, but not everyone knows enough baseball to figure this out.

**Comment by Sakimori** [comment]
this is a great idea. probably not _there_ but i'll find space in the embed somewhere!

**Comment by Sakimori** [comment]
ah. moving weather to a field in the embed, and adding team at bat to the footer. will do
