### ISSUE TITLE
feature request: league weather control

### ISSUE THREAD

**Issue by valuminumbandit** [Sakimori/matteo-the-prestige#246]
howdy! i love the league weather system so much (especially random sun explosion and the like). a feature request: in the startleague command, a tag for disabling certain weathers leaguewide until the league is stopped! if you stop enough weathers you're basically forcing certain ones, but i think it'd also be useful for folks who don't like a few specific weathers for one reason or another.

i think it'd be neat to have catastrophic stretches of league where all the weather is angry, that i can control for plot reasons

**Comment by Sakimori** [comment]
please do not suggest features like this

**Comment by Sakimori** [comment]
i should clarify: not via this method.
