### ISSUE TITLE
If a player has a hyphen for the last letter in their first name, showing their stats does not work

### ISSUE THREAD

**Issue by Genderdruid** [Sakimori/matteo-the-prestige#256]
Examples:
m;showplayer Plas-i- Carw-sh
m;showplayer ---pect- I--pec---g
m;showplayer Test- 1

**Comment by Sakimori** [comment]
I strongly suspect this is a discord or html issue and not a sim16 problem but I'll do some investigating

**Comment by Sakimori** [comment]
it's a problem with how I get names from onomancer, fix: don't put hyphens at the end of names
