### ISSUE TITLE
links posted by matteo appear to use an outdated format

### ISSUE THREAD

**Issue by Genderdruid** [Sakimori/matteo-the-prestige#258]
individual games on the website use the main url (slash) game (slash) the specific numbers and letters to identify the game, while the the bot uses the main url (slash) ?game= and then the numbers and letters. clicking on this sends you to all games

**Comment by Sakimori** [comment]
this is intentional, the bot link takes you to all games with the desired game forced to the top-left spot while the share link is JUST one game with short history
