### ISSUE TITLE
new onomancer team import!! 

### ISSUE THREAD

**Issue by Sakimori** [Sakimori/matteo-the-prestige#26]

**Comment by esSteres** [comment]
Some questions: 

- where to add this? as an option under `m;saveteam` or as its own command? I feel like the former makes more sense but unsure
- should there be a separate collection cache or do we just enter the players into the existing player cache individually?
- onomancer collections can have multiple pitchers but the simsim doesn't support that. do we just take the first pitcher? do we only accept collections with only one rotation member? do we want to add multiple pitcher functionality?

**Comment by Sakimori** [comment]
i've been imagining this as an `m;import` command, where it converts the onomancer collection into a team object and saves it as normal. as far as your last point: i think ch00beh is working on a specific matteo mode for my use

**Comment by esSteres** [comment]
so are we going to say that this is waiting on #55?

**Comment by esSteres** [comment]
I have a pretty much complete version of this, though I haven't done any caching. I think it's reasonable to at least cache each player from the team individually, but adding a new cache just for collections might be overkill for this one feature. although there's a soulscream cache already so maybe?

**Comment by Sakimori** [comment]
the soulscream cache is the entire reason the simsim exists. i wanted to make a "press button get soulscream" bot and it kind of just spiraled out of control from there. caching the players individually should be fine
