### ISSUE TITLE
Show total innings in final game results

### ISSUE THREAD

**Issue by ifhbiff** [Sakimori/matteo-the-prestige#29]
The "Final Score" box for the post doesn't show the # of innings played ... there's currently no way to recognize when a game went into extra innings.

**Comment by Sakimori** [comment]
potentially add box score somehow, shame/victory lap occurrences to summary. plenty of free space in that embed

**Comment by Sakimori** [comment]
will make new issue for box score at some point in future, in the meantime the innings + shame/victory lap have been addressed.
