### ISSUE TITLE
Pull "real" player stats when applicable

### ISSUE THREAD

**Issue by xSke** [Sakimori/matteo-the-prestige#31]
similar how to the onomancer frontend works. probably not too bad requests-wise since you already have a caching system in place?

**Comment by xSke** [comment]
this would also allow stopping/resuming games past restarts since if you save the game state in the database anyway, you can pull the latest state and continue from there

**Comment by robbyblum** [comment]
quoth ch00beh on discord:
> i wonder if matteo should use mike directly instead of hopping over http to onomancer since i probably won't be touching the onomancer reflection algo (it's just json serialization and finger calc) anytime soon since it seems to be working
