### ISSUE TITLE
"m;showplayer Redeposit Bullfighting" doesn't seem to work

### ISSUE THREAD

**Issue by robbyblum** [Sakimori/matteo-the-prestige#35]
They're a very bad player, maybe this is part of it?

**Comment by robbyblum** [comment]
`m!showplayer Unchalked Compassable` also doesn't work. Their pitching stats: https://i.imgur.com/B6NbgYU.png. So, may be a zero-star player issue...

**Comment by Sakimori** [comment]
bug confirmed, will fix

**Comment by Sakimori** [comment]
build_star_embed at line 113 of the_prestige is trying to build a field with 0 stars. simple enough fix

**Comment by robbyblum** [comment]
I should be able to fix it, just cloning and setting up my environment and all that jazz so that I can test my edits properly before opening a PR.
