### ISSUE TITLE
make showteam more forgiving

### ISSUE THREAD

**Issue by esSteres** [Sakimori/matteo-the-prestige#42]
show team is pretty tight about case and such right now. If a showteam call isn't a team name, but searching the db using that name as a query (maybe after shifting to all lower case as well?) returns only one result, could we just display that team as though they had gotten it exactly?
i.e. if I type `m;showteam example` but the team I want is called `Exeter Examples`, currently it would error. I propose that if `db.search_teams("example")` would return only `Exeter Examples`, we should just display them as though that was what was typed.

**Comment by Sakimori** [comment]
great idea. i'll do that right now

**Comment by Sakimori** [comment]
or you can, since you're already working on commands
