### ISSUE TITLE
optionally assign defensive positions to players

### ISSUE THREAD

**Issue by Sakimori** [Sakimori/matteo-the-prestige#64]

**Comment by esSteres** [comment]
this sounds like a backend thing. Is there a reason this is tagged as 'website'?

**Comment by Sakimori** [comment]
it might be a little tedious to do on discord, so i tagged it as website because we _might_ need an input page for this. i have had a few ideas for discord though so maybe not

**Comment by Sakimori** [comment]
current idea: categories in code as just "infield, outfield, catcher" with player naming their positions however they like (except catcher)

catcher will be used to stop all steals
outfield won't get groundouts
infield flyouts will have text changed to "pops out" instead of "flies out"

**Comment by Sakimori** [comment]
no longer in scope
