### ISSUE TITLE
how do we want to handle games ending on the wobsite?

### ISSUE THREAD

**Issue by Sakimori** [Sakimori/matteo-the-prestige#73]

**Comment by Sakimori** [comment]
my idea is have matteo post the same final box in discord, and have the game box stick around on-site for a minute or so. game updates already have a delay value to give people time to get back to the site before the game starts so we can use that to keep the box around until it's deleted

**Comment by Sakimori** [comment]
open to suggestions on this though

**Comment by esSteres** [comment]
sounds good to me; I'd have to actually uhhhh implement that delay feature but that shouldn't be hard
(I saw the value earlier but wasn't sure what it was for)

**Comment by Sakimori** [comment]
alright, i'll have main_controller start incrementing it back up after the game ends. note that on live it'll be multiplied by 6 because it's once per tick
