### ISSUE TITLE
trailing spaces for team names in startgames resulting in no team found

### ISSUE THREAD

**Issue by Sakimori** [Sakimori/matteo-the-prestige#78]

**Comment by esSteres** [comment]
I feel like we may want to make a single `get_team` function to use everywhere that has the behavior that `showteam` has currently, where if searching with the given string returns only one team we can assume that's the team they meant

**Comment by Sakimori** [comment]
i was thinking the same thing. i'll do that after #partytime before working on pitcher rotations
